name: LookingGlassAutomation

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Type plan, apply or destroy'
        required: true
        default: 'plan'
      environment:
        description: 'Type the environment (e.g., dev, prod)'
        required: true
        default: 'dev'

permissions:
  contents: read

env:
  TF_ENV: ${{ github.event.inputs.environment || 'dev' }}
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
  TF_DIR: looking_glass/environment/dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        env:
          name: plan-approval
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Plan
        if: github.event_name == 'push' || github.event.inputs.action == 'plan'
        run: terraform plan -var-file=dev.tfvars
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -var-file=dev.tfvars -auto-approve
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform Destroy
        env:
          name: destroy-approval
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -var-file=dev.tfvars -auto-approve
        working-directory: ${{ env.TF_DIR }}
